// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_Inventario.Datos;

#nullable disable

namespace Sistema_Inventario.Migrations
{
    [DbContext(typeof(ApplicationDbContext.ApplicationDbContexto))]
    [Migration("20230820020201_intialCreate")]
    partial class intialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sistema_Inventario.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("categorias");
                });

            modelBuilder.Entity("Sistema_Inventario.Models.Persona", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Barrio")
                        .HasColumnType("int");

                    b.Property<int>("Canton")
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Distrito")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtraDireccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Provincia")
                        .HasColumnType("int");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoIdentificacion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Sistema_Inventario.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadActual")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Costo")
                        .HasColumnType("real");

                    b.Property<float>("Descuento")
                        .HasColumnType("real");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<decimal>("Impuesto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<float>("PrecioVenta")
                        .HasColumnType("real");

                    b.Property<float>("Utilidad")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("productos");
                });

            modelBuilder.Entity("Sistema_Inventario.Models.tbBarrios", b =>
                {
                    b.Property<string>("ProvinciaID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<string>("CantonID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(2);

                    b.Property<string>("DistritoID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(3);

                    b.Property<string>("Barrio")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(4);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinciaID", "CantonID", "DistritoID", "Barrio");

                    b.ToTable("tbBarrios");
                });

            modelBuilder.Entity("Sistema_Inventario.Models.tbCanton", b =>
                {
                    b.Property<string>("ProvinciaID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<string>("Canton")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(2);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbProvinciaCod")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProvinciaID", "Canton");

                    b.HasIndex("tbProvinciaCod");

                    b.ToTable("tbCantones");
                });

            modelBuilder.Entity("Sistema_Inventario.Models.tbDistrito", b =>
                {
                    b.Property<string>("ProvinciaID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<string>("CantonID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(2);

                    b.Property<string>("Distrito")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(3);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinciaID", "CantonID", "Distrito");

                    b.ToTable("tbDistritos");
                });

            modelBuilder.Entity("Sistema_Inventario.Models.tbProvincia", b =>
                {
                    b.Property<string>("Cod")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cod");

                    b.ToTable("tbProvincias");
                });

            modelBuilder.Entity("Sistema_Inventario.Models.Cliente", b =>
                {
                    b.HasBaseType("Sistema_Inventario.Models.Persona");

                    b.Property<float>("CreditoMaximo")
                        .HasColumnType("real");

                    b.Property<int>("cantidadDiasCredito")
                        .HasColumnType("int");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("Sistema_Inventario.Models.Producto", b =>
                {
                    b.HasOne("Sistema_Inventario.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Sistema_Inventario.Models.tbBarrios", b =>
                {
                    b.HasOne("Sistema_Inventario.Models.tbDistrito", "Distrito")
                        .WithMany("Barrios")
                        .HasForeignKey("ProvinciaID", "CantonID", "DistritoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distrito");
                });

            modelBuilder.Entity("Sistema_Inventario.Models.tbCanton", b =>
                {
                    b.HasOne("Sistema_Inventario.Models.tbProvincia", null)
                        .WithMany("Cantones")
                        .HasForeignKey("tbProvinciaCod");
                });

            modelBuilder.Entity("Sistema_Inventario.Models.tbDistrito", b =>
                {
                    b.HasOne("Sistema_Inventario.Models.tbCanton", "Canton")
                        .WithMany("Distritos")
                        .HasForeignKey("ProvinciaID", "CantonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canton");
                });

            modelBuilder.Entity("Sistema_Inventario.Models.Cliente", b =>
                {
                    b.HasOne("Sistema_Inventario.Models.Persona", null)
                        .WithOne()
                        .HasForeignKey("Sistema_Inventario.Models.Cliente", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sistema_Inventario.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Sistema_Inventario.Models.tbCanton", b =>
                {
                    b.Navigation("Distritos");
                });

            modelBuilder.Entity("Sistema_Inventario.Models.tbDistrito", b =>
                {
                    b.Navigation("Barrios");
                });

            modelBuilder.Entity("Sistema_Inventario.Models.tbProvincia", b =>
                {
                    b.Navigation("Cantones");
                });
#pragma warning restore 612, 618
        }
    }
}
